= Moxy

image:https://img.shields.io/badge/vert.x-3.5.3-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./mvnw clean test
```

To package your application:
```
./mvnw clean package
```

To run your application:
```
./mvnw clean exec:java
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]


jcmd 20097 PerfCounter.print | grep sun.management.JMXConnectorServer.address
sun.management.JMXConnectorServer.address="service:jmx:rmi://127.0.0.1/stub/rO0ABXN9AAAAAQAlamF2YXgubWFuYWdlbWVudC5yZW1vdGUucm1pLlJNSVNlcnZlcnhyABdqYXZhLmxhbmcucmVmbGVjdC5Qcm94eeEn2iDMEEPLAgABTAABaHQAJUxqYXZhL2xhbmcvcmVmbGVjdC9JbnZvY2F0aW9uSGFuZGxlcjt4cHNyAC1qYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN0SW52b2NhdGlvbkhhbmRsZXIAAAAAAAAAAgIAAHhyABxqYXZhLnJtaS5zZXJ2ZXIuUmVtb3RlT2JqZWN002G0kQxhMx4DAAB4cHcyAApVbmljYXN0UmVmAAkxMjcuMC4wLjEAAKFj3grabr/F9WJHz8xTAAABaKuY7daAAgB4"

curl -vi -XPOST -H "Content-Type: application/json" -d'{"configuration":"tomcat","jmxUrl":"jmx://foobar"}' http://localhost:8080/nodes/i
curl -vi -XPOST -H "Content-Type: application/json" -d'{"configFile":"C:/work/projects/moxy/src/main/resources/tomcat.yml","jmxUrl":"jmx://foobar"}' http://localhost:8080/nodes/i
curl -vi -XPOST -H "Content-Type: application/json" -d'{"configFile":"C:/work/projects/moxy/src/main/resources/tomcat.yml"}' http://localhost:8080/nodes/a
